apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: zavora
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: ${REGISTRY_URL}/zavora/account-service:${TAG}
        env:
        - name: DATABASE_URL
          value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/zavora
        - name: REDIS_URL
          value: redis://redis:6379
        - name: RUST_LOG
          value: info
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: zavora
spec:
  selector:
    app: account-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP