apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-engine
  namespace: zavora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-engine
  template:
    metadata:
      labels:
        app: trading-engine
    spec:
      containers:
      - name: trading-engine
        image: ${REGISTRY_URL}/zavora/trading-engine:${TAG}
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/zavora
        - name: REDIS_URL
          value: redis://redis:6379
        - name: RUST_LOG
          value: info
        - name: PORT
          value: "8080"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        resources:
          limits:
            memory: 1Gi
            cpu: 1000m
          requests:
            memory: 512Mi
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: trading-engine
  namespace: zavora
spec:
  selector:
    app: trading-engine
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP