version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: viabtc
      POSTGRES_PASSWORD: viabtc
      POSTGRES_DB: viabtc
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  postgres_test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: viabtc
      POSTGRES_PASSWORD: viabtc
      POSTGRES_DB: viabtc_test
    ports:
      - "5434:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  trading-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://viabtc:viabtc@postgres:5432/viabtc
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=info
      - PORT=8080
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data: