apiVersion: v1
kind: Secret
metadata:
  name: zavora-secrets
  namespace: zavora
type: Opaque
stringData:
  DATABASE_URL: "postgres://zavora:zavora@zavora-postgres-dev.c87kigjyeqet.us-west-2.rds.amazonaws.com:5432/zavora"
  REDIS_URL: "redis://zavora-redis-dev.xxxxx.ng.0001.usw2.cache.amazonaws.com:6379" 